sudo: required
services:
  - docker

before_install:
  - docker build -t nj14/react-test -f ./client/Dockerfile.dev ./client

script:
  docker run nj14/react-test npm test -- --coverage

after_success:
  - docker build -t nj14/multi-client -f ./client
  - docker build -t nj14/multi-nginx -f ./nginx
  - docker build -t nj14/multi-server -f ./server
  - docker build -t nj14/multi-worker -f ./worker
# Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
  - docker push nj14/multi-client
  - docker push nj14/multi-nginx
  - docker push nj14/multi-server
  - docker push nj14/multi-worker

